// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    OrgBlockComp: typeof import('./components/org/OrgBlockComp.vue')['default']
    OrgColorTextComp: typeof import('./components/org/OrgColorTextComp.vue')['default']
    OrgContentComp: typeof import('./components/org/OrgContentComp.vue')['default']
    OrgDocComp: typeof import('./components/org/OrgDocComp.vue')['default']
    OrgEmphasisComp: typeof import('./components/org/OrgEmphasisComp.vue')['default']
    OrgHeaderComp: typeof import('./components/org/OrgHeaderComp.vue')['default']
    OrgListComp: typeof import('./components/org/OrgListComp.vue')['default']
    OrgMaybeComp: typeof import('./components/org/OrgMaybeComp.vue')['default']
    OrgStateWordComp: typeof import('./components/org/OrgStateWordComp.vue')['default']
    OrgSubSupComp: typeof import('./components/org/OrgSubSupComp.vue')['default']
    OrgTableComp: typeof import('./components/org/OrgTableComp.vue')['default']
    OrgTextComp: typeof import('./components/org/OrgTextComp.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
