// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    OrgColorfulTextNode: typeof import('./components/org/OrgColorfulTextNode.vue')['default']
    OrgContentNode: typeof import('./components/org/OrgContentNode.vue')['default']
    OrgEmphasisNode: typeof import('./components/org/OrgEmphasisNode.vue')['default']
    OrgHeaderNode: typeof import('./components/org/OrgHeaderNode.vue')['default']
    OrgSubSupNode: typeof import('./components/org/OrgSubSupNode.vue')['default']
    OrgTextNode: typeof import('./components/org/OrgTextNode.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
