// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    OrgBlock: typeof import('./components/org/OrgBlock.vue')['default']
    OrgBlockComp: typeof import('./components/org/OrgBlockComp.vue')['default']
    OrgContent: typeof import('./components/org/OrgContent.vue')['default']
    OrgContentComp: typeof import('./components/org/OrgContentComp.vue')['default']
    OrgEmphasisComp: typeof import('./components/org/OrgEmphasisComp.vue')['default']
    OrgHeaderComp: typeof import('./components/org/OrgHeaderComp.vue')['default']
    OrgSubSupComp: typeof import('./components/org/OrgSubSupComp.vue')['default']
    OrgTableComp: typeof import('./components/org/OrgTableComp.vue')['default']
    OrgTextComp: typeof import('./components/org/OrgTextComp.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
